version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=secretpassword
    ports:
      - "5432:5432"
